.catalog:
    name: "foo"
    version: "v0.1"
    minimum_rancher_version: v0.51.0
    questions:
        - variable: scale
          description: "Initial scale for frontend"
          label: "Frontend Scale"
          required: true
          default: 1
          type: "int"
loadbalancer:
    start_on_create: true
    scale: 1
    lb_config:
      port_rules:
      - source_port: 80
        target_port: 5000
        service: web
    health_check:
      port: 42
      interval: 2000
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000
web:
    scale: ${scale}
redis:
    scale: 1
